<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Waraq.Windows.Host</RootNamespace>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Waraq.Windows.Core\Waraq.Windows.Core.csproj" />
  </ItemGroup>
</Project>
